Support new error response standard (#8)
Instead of returning `{}`, the API will return the following error format for most endpoints:
```json
{
  error: "Something went wrong",
  reason: "this is why"
}
```